insert into products_info(id, description, publisher, weight, number_of_pages)
values (1,
        'For twin sisters Rose and Bel, enrolling at the prestigious new boarding school should have been a fresh start. But with its sinister rituals and traditions, Odell soon brings out a deadly rivalry between the sisters.',
        'Harper', 0.310, 448),
       (2,
        'It''s been nearly a year since everything happened between Magnolia Parks and BJ Ballentine on the steps of the Mandarin Oriental, and it seems like everything since then has changed.',
        'Hastins', 0.650, 234),
       (3,
        'Daisy Haites thought she''d left everything about her old life in the past: the crime, her family and the man she loves. But when her safety is threatened once again, she finds herself back under the watchful eyes of her gang-lord brother Julian and her ex-boyfriend Christian, both desperate to keep her safe.',
        'Hastins', 0.480, 384),
       (4, 'THE SUNDAY TIMES NO.1 BESTSELLER
SIMON MAYO RADIO 2 BOOK CLUB CHOICE
RADIO 4 BOOK AT BEDTIME
GOODREADS CHOICE AWARDS BEST MYSTERY & THRILLER 2017', 'World Publishers Ltd', 0.621, 368),
       (5,
        'BOOK 16 IN THE EPIC HISTORICAL SAGA OF THE COURTNEY FAMILY, FROM INTERNATIONAL BESTSELLER WILBUR SMITH ''Best historical novelist'' - Stephen King ''A Master Storyteller'' - Sunday Times ''Wilbur Smith is one of those benchmarks against whom others are compared'' -The Times ''No one does adventure quite like Smith'' - Daily Mirror TWO HEROES. ONE UNBREAKABLE BOND. Torn apart by war, Saffron Courtney and Gerhard von Meerbach are thousands of miles apart, both struggling for their lives.',
        'James', 0.760, 464),
       (6,
        'Young adventurers Patrice and Nate have followed neighborhood defender Crazy Dave throughout time--but are they ready to investigate a school campus to keep the streets safe from zombies? In Plants vs. Zombies: Bully For You, they''ll be visiting a very strange college in an attempt to take down Dr. Zomboss yet again--and any school visit''s tolerable if you get to battle zombies!',
        'Dark Horse Comics', 0.455, 96),
       (7,
        'Ten days to Christmas and Tracey Uphill, aged eight, hasn''t come home from Sunday school. Her mother, a pretty young prostitute, is desperate. Enter Detective Inspector Jack Frost, sloppy, scruffy and insubordinate.',
        'Transworld Publishers Ltd', 0.354, 239),
       (8,
        'Britain''s former prime minister is holed up in a remote, ocean-front house in America, struggling to finish his memoirs, when his long-term assistant drowns. A professional ghostwriter is sent out to rescue the project - a man more used to working with fading rock stars and minor celebrities than ex-world leaders.',
        'ColdStone', 0.281, 416),
       (9,
        'Tilly Trotter seems to have finally found lasting happiness in her engagement to Steve McGrath. But just as everything falls into place for Tilly it seems to be falling apart for her loved ones...',
        'ColdStone', 0.376, 448),
       (10,
        'Sci-fi fans will love the detail and the optimism about humanity''s future in space'' - Wall Street Journal',
        'Little', 0.376, 480),
       (11,
        'Sumptuous slipcased edition of Tolkien''s classic epic tale of adventure, fully illustrated in colour for the first time by the author himself. This deluxe volume is quarterbound in leather and includes many special features unique to this edition.
Since it was first published in 1954, The Lord of the Rings has been a book people have treasured.',
        'Little', 1.990, 1248),
       (12,
        'Discover The Atlas Paradox, the electric dark academia sequel to viral sensation The Atlas Six by Olivie Blake - a No.1 Sunday Times bestseller. Inside the Alexandrian Society alliances will be tested, hearts will be broken and all must pick a side.',
        'Orion Publishing Co', 0.780, 332),
       (13,
        'Experience the world of the Witcher like never before with this stunning deluxe hardcover edition of The Last Wish!
Featuring seven gorgeous illustrations from seven award-winning artists - one for each story in the collection of adventures - it celebrates the first chapter of the bestselling, groundbreaking series that inspired the hit Netflix show and the blockbuster video games.',
        'Pan Macmillan', 0.640, 432),
       (14,
        'In The Curse of Oak Island, longtime Rolling Stone contributing editor and journalist Randall Sullivan explored the curious history of Oak Island and the generations of people who tried and failed to unlock its secrets. Drawing on his exclusive access to Marty and Rick Lagina, stars of the History Channel''s television show The Curse of Oak Island, Sullivan delivers an up to the minute chronicle of their ongoing search for the truth.',
        'Grove Press', 0.460, 416),
       (15,
        'The definitive guide to Java programming-thoroughly revised for Java SE 17',
        'McGraw-Hill Education', 1.820, 1280),
       (16,
        'Lonely Planet''s South India & Kerala is your passport to the most relevant, up-to-date advice on what to see and skip, and what hidden discoveries await you. Floa',
        'McGraw-Hill Education', 0.460, 560),
       (17,
        'Coloring the body and its systems is the most effective way to study the structure and functions of human anatomy. Kaplan Medical''s Anatomy Coloring Book provides realistic drawings, clear descriptions, and must-know terms for an easy way to learn anatomy and physiology. Realistic anatomy coloring book for pre-health students and others learning anatomy.',
        'Kaplan Publishing', 1.021, 348),
       (18,
        '"Best known for his unique musical style and blindingly fast hybrid picking technique, English guitarist Albert Lee is often referred to within the music industry as the """"guitar player''s guitar player,"""" renowned for his work across several genres of music and for the respect that he has garnered from other industry giants.',
        'Kaplan Publishing', 0.701, 279),
       (19,
        'Learn to read with the official Minecraft Young Readers! Practise your reading skills and develop your vocabulary as you read stories about your favourite game.',
        'Kaplan Publishing', 0.084, 32),
       (20,
        'It is 1911, and Jean is about to join the mass strike at the Singer factory. For her, nothing will be the same again. Decades later, in Edinburgh, Connie sews coded moments of her life into a notebook, as her mother did before her.',
        'Unbound Digital', 0.340, 368);

update product_info_seq set next_val=21 where next_val=1